- gopowerstore_types.go
> nfs export error updated

- .github/CODEOWNERS
- host_types.go
- inttests/replication_test.go
- volume_test.go
- volume_types.go
| |
Added support for latest OE
> Added support for latest OE

- host_types.go
> Adding NVMe protocol type for host initiator

- .github/workflows/actions.yml
- inttests/common.go
| |
Update workflow and fix gosec reported issue
> Update workflow and fix gosec reported issue

- client.go
- fs.go
- fs_types.go
- mocks/Client.go
List the GitHub issues impacted by this PR: 
|dell/csm#191 |
PowerStore API wrapper calls added for NFSv4 ACL support
> Query APIs needed for NFSv4 acl support

- go.mod
- gopowerstore_types.go
| |
When the external access parameter is set in values.yaml idempotency check was failing - This will address that issue
> HTTP error code update

- gopowerstore_types.go
| https://github.com/dell/csm/issues/176 |
Added retry mechanism with an idempotency check for NFS for the latest array
> Added retry idempotency for NFS

- client.go
- cluster.go
- cluster_types.go
- fc_port.go
- software_installed.go
|https://github.com/dell/csm/issues/260|
Added a new parameter to the REST API call api/rest/cluster for the adding the NVMe subsystem NQN for NVMe devices. Since the value is added only on Powerstore 3.0, check has been provided for the same. 
A single function GetSoftwareMajorVersion was created to remove the duplicity in the code.
> NVMeFC NQN Changes

- mocks/Client.go
|dell/csm#260 |
Adding mock function to GetSoftwareMajorMinorVersion API added in PR#73
> Adding mock function for GetSoftwareMajorMinorVersion API

- go.mod
| |
updated go version to 1.18
> updated go version to 1.18

- fs_types.go
- volume_types.go
| dell/csm#291|
PowerStore configurable volume attributes addition to Volume/FS Creation types
> PowerStore configurable volume attributes

- fs_types.go
- volume_types.go
| dell/csm#291|
Support backward compatibility of FSCreate type
> Configurable vol attributes

- gopowerstore_types.go
| dell/csm#291 |
FS name already exists gives specific error - 402 Unprocessable entity error. 
400 Bad request shouldn't be part of FS name check.
> Fixing incorrect error message

- metrics.go
- metrics_test.go
| https://github.com/dell/csm/issues/483 |
Updated GetCapacity gRPC call to return array's available capacity.
> Storage Capacity Tracking - Updated GetCapacity gRPC call to return array's available capacity

- client.go
- fs_types.go
- volume.go
- volume_test.go
- volume_types.go
| [dell/csm#538](https://github.com/dell/csm/issues/538) |
Added GetAppliance and GetApplianceByName functions and other respective additions done in order to get the service tag displayed in the PV volume attributes.
> Added GetAppliance and GetApplianceByName functions for fetching service tag 

- mocks/Client.go
| [dell/csm#538](https://github.com/dell/csm/issues/538) |
Added mock functions GetAppliance & GetApplianceByName in mocks/Client.go
> Added mock functions GetAppliance & GetApplianceByName in Client.go

- api/api.go
- api/api_test.go
- client.go
- client_options.go
- examples/simple/main.go
- fc_port.go
- fc_port_types.go
- fs.go
- fs_test.go
- fs_types.go
- gopowerstore_types.go
- gopowerstore_types_test.go
- host_types.go
- inttests/common.go
- inttests/fs_test.go
- inttests/metrics_test.go
- inttests/nfs_test.go
- ip_pool_address_test.go
- ip_pool_address_types.go
- metrics.go
- metrics_test.go
- metrics_types.go
- nfs.go
- nfs_test.go
- nfs_types.go
- volume.go
- volume_test.go
- volume_types.go
|https://github.com/dell/csm/issues/491|
- Update incorrect copyright years.
> Update copyright for existing files

- ip_pool_address.go
- metrics.go
| |
Instead of using any new local variable keep the same logic how we have did in other places.
> gopowerstore client enhancement

- host_group.go
- host_group_types.go
- host_types.go
- replication_types.go
- volume_types.go
| https://github.com/dell/csm/issues/623 |
Host group get API call updated and for protection policy id "" was getting ignored due to omitempty which is now fixed,
> Minor changes for terraform for powerstore bugfix

- api/api.go
- go.mod
|https://github.com/dell/csm/issues/658|
Go version update from 1.19 to 1.20
> Go version update from 1.19 to 1.20

- mocks/Client.go
| |
<Added mock function by mockery tool>
Ran make test in csi-powerstore repo that was pointing out to this commit and all tests passed as per the expectation.
> Adding mock function

- client.go
- host_group.go
- host_group_test.go
- host_group_types.go
- host_types.go
- replication.go
- replication_test.go
- replication_types.go
- snapshot_rule_types.go
- volume_group.go
- volume_group_test.go
- volume_group_types.go
| https://github.com/dell/csm/issues/623 |
- Added "GetProtectionPolicies" method which will return list of all protection policies and added supported attributes in ProtectionPolicy struct.
- Added is_write_order_consistent attribute to volume group struct
- Added protection policy attribute to snapshot rule struct
- Added host_connectivity attribute to host resource struct
- Added name and is_write_order_consistent attribute to VolumeGroupModify struct
- Added required attributes and methods for volume group data source
- Added required attributes and methods for host group resource
- Added required attributes for host data source
> Changes for terraform provider for PowerStore

- client.go
- fs.go
- fs_types.go
- replication_types.go
| [639](https://github.com/dell/csm/issues/639) |
Several NAS-related changes, including a function to update a NAS server's protection policy. Plus, additional fields in file-replication related objects (NAS, protection policy)
> Added support for several NAS related commands

- go.mod
- go.sum
|https://github.com/dell/csm/issues/885|
Go version update
> Go version update

- replication_types.go
|https://github.com/dell/csm/issues/1109|
- Removing omitEmpty from Failover Param as it was getting removed if it was false
> Remove omitEmpty from failover param

- .github/workflows/actions.yml
- .github/workflows/linters.yaml
- client_options_test.go
- client_test.go
Fix Client unit tests by using api.ContextKey type.
| https://github.com/dell/csm/issues/1091|
Use api.ContextKey type.
> Fix unit tests

- gopowerstore_types.go
- gopowerstore_types_test.go
| https://github.com/dell/csm/issues/1443 |
Added new error for https://github.com/dell/csi-powerstore/pull/344
Tested along with powerstore driver changes.
Unit tests added (coverage: 81.9% of statements).
> New error for Metro volume create

- replication_types.go
| https://github.com/dell/csm/issues/1443 |
Adding new Metro session states as required.
Tested as part of https://github.com/dell/csi-powerstore/pull/350
> Updating Metro session states

- fs_types.go
| https://github.com/dell/terraform-provider-powerstore/pull/121 |
Add attribute to FileSystem Snapshot
> Terraform Feature/filesystem snapshot

- fs_types.go
https://github.com/dell/terraform-provider-powerstore/issues/120
| |
<your change goes here>
> removed omitempty

- fs_types.go
> Added omitempty to FSModify Type [Revert]

- fs_types.go
| |
added some more attributes in the file system get call as I need to fetch all the attributes whatever is present in the actual paylod
> added some more attributes for file system get call

- .github/workflows/release.yaml
|https://github.com/dell/csm/issues/1490 |
Added secret inheritance for release action
Tested against fork: https://github.com/harishp8889/test-gofsutil-automation/actions/runs/12724867954/job/35471506833
> added secret inherit

- client.go
- nfs.go
- nfs_test.go
| https://github.com/dell/terraform-provider-powerstore/issues/120 |
add methods to get NFS by id and filter
> added get nfs export by id and filter

- client.go
- fs.go
- fs_test.go
- fs_types.go
- inttests/fs_test.go
Added methods and tests to get All NAS Servers
> added get all nas servers

- Makefile
This PR adds Makefile targets to run GitHub Actions checks locally:
`actions` Target :
Runs all pull request checks with enhanced logging.
`action-help` Target :
Displays instructions for running specific workflows with act.
Usage:
Run all PR checks: `make actions`
Get workflow instructions: `make action-help`
Enhances local testing and debugging of GitHub Actions.
| https://github.com/dell/csm/issues/1490|
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration
> Gopowerstore/Add Makefile Targets for Local PR Checks

- client.go
- smb_share.go
- smb_share_test.go
| https://github.com/dell/terraform-provider-powerstore/issues/120 |
Adding function to fetch SMB share collection.
> Adding function to fetch SMB share collection

- client.go
- cluster.go
- cluster_test.go
- cluster_types.go
- inttests/replication_sync_test.go
| https://github.com/dell/terraform-provider-powerstore/issues/120 |
Adding method to filter remote systems by any filters
```
root@lglap049:~/gopowerstore# go test ./inttests/ -run TestGetRemoteSystems
ok      github.com/dell/gopowerstore/inttests   0.281s
root@lglap049:~/gopowerstore#
```
> Adding method to filter remote systems by any filters
